name: Feature request
about: Suggest an idea for this project
title: ""
type: feature
assignees:
  - lemonpole
projects:
  - playliga/2
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the feature you would to see.
      placeholder: Please enter details.
    validations:
      required: true
